README.md
=> Add codecov coverage badge to README

__init__.py, ext.py
Keep them available from the old location, w/ added DeprecationWarnings
See #29 for details
=> Move dxtbx extensions from dxtbx.* to dxtbx.ext.*

format/FormatCBFMultiTileHierarchy.py
=> Fix format class hierarchy

format/FormatTIFF.py, format/FormatTIFFHelpers.py, format/FormatTIFFRayonixSPring8.py, format/FormatTIFFRayonixXPP.py
I discovered a few inefficiencies in the `understand()` methods.
Also address string/byte issues while being here.
=> TIFF format class refactoring

command_line/plot_detector_models.py, format/FormatCBFFullPilatusDLS300KSN104.py, format/FormatCBFFullPilatusDLS6MSN100.py, format/FormatCBFMiniPilatusDLS6MSN100.py, format/FormatHDF5SaclaMPCCD.py, sweep_filenames.py
This pull request is based on the `lib2to3.fixes.fix_zip` fixer, which is very similar to #43. in Python 3 `zip()` returns a `zip` object, which basically is an iterator. The automatic fixer wraps every `zip()` call in `list()` to restore previous behaviour.
=> Python 3: lib2to3.fixes.fix_zip

format/FormatRAXIS.py, format/FormatRAXISII.py, format/FormatRAXISIVSpring8.py, libtbx_refresh.py
there are the usual byte/string bits, but a cursory glance suggested there may be some code overlap between classes, too.
=> Python 3: RAXIS format class update/refactoring

model/boost_python/panel.cc, model/boost_python/pixel_to_millimeter.cc, model/panel.h, model/parallax_correction.h, model/pixel_to_millimeter.h
=> Calculate attenuation length per shoebox instead of per pixel

data/detectors.lib, format/FormatNexusJungfrauHack.py, format/nexus.py
Contains hacks, needs squash merge, does not strictly require the changes which happened in `nexus.py` I think so those could be reverted. `FormatNexus.py` change needed to stop this being pulled out as stills. The rest of this is working around deficiencies in the existing file format.
Certainly this needs squash merge and a better commit history. In the long game this format class should be transient.
=> Jungfrau 1M support for rotation data

format/FormatSMVADSC.py, format/FormatSMVADSCSN445.py, format/FormatSMVADSCSN905.py, format/FormatSMVADSCSN915.py, format/FormatSMVADSCSN920.py, format/FormatSMVJHSim.py, format/FormatSMVRigakuSaturnNoTS.py, imageset.h, newsfragments/108.bugfix, tests/test_imageset.py
These changes fix the use of a per-panel pedestal, simplify the logic determining whether to construct a pedestal map and allow negative pedestal values.
=> Fix panel pedestal

format/nexus.py, newsfragments/119.bugfix
=> Add VMXi EIGER1 to known_backwards list

format/FormatNexusEigerDLS16M.py
At the moment this is not linkable from the proper h5 file structure however
is included in the meta file as the config dataset, a text file which
comes from the detector - look this up as a workaround
If *anything* goes wrong, ignore by design
=> For i03-365 - look for cutoff in meta file

format/FormatCBFCspad.py, format/FormatCBFFull.py
- Fixes recursive_sync, a function used by cctbx.xfel.xtc_process
- Fixes get_raw_data for FormatCBFFull.py
=> Py3 fixes for cbf

format/FormatCBFMultiTile.py, format/cbf_writer.py
Made a nanoBragg cbf writer however it required these changes to be Python2/3 compatible. See cctbx branch nanoBragg_cbfwrite for the nanoBragg writer code in simtbx/nanoBragg (tst_nanoBragg_cbf_write.py)
=> py 3 compat code, came across when making nanoBragg cbf writer

model/boost_python/detector.cc, model/detector.h
WIP - while looking at issues relating to `mask.pickle` and https://github.com/cctbx/dxtbx/issues/182 saw some need for housekeeping - fix typo, remove large blocks of `/* commented out code */`
=> Housekeeping

format/FormatCBFFull.py, format/FormatHDF5EigerNearlyNexus.py, format/FormatHDF5SaclaMPCCD.py, format/FormatHDF5SaclaRayonix.py, format/FormatNexusJungfrauHack.py, util/dlsnxs2cbf.py
Follow the convention of importing `numpy as np`
=> Change numpy import commands

tests/format/test_FormatHDF5EigerNearlyNexus.py, tests/serialize/test_xds.py
Accounts for changes in fundamental constants in
https://github.com/cctbx/cctbx_project/commit/9f2530bc8f2a6b693bdb2d36b276049d24956c0a
Fixes #202
Should also work with previous values.
=> Update tests for changes for attenuation lengths from constant update

ext.py, format/FormatBrukerPhotonII.py, format/FormatCBFMini.py, format/FormatGatanDM4.py, format/FormatSER.py, format/FormatSMV.py, format/FormatSMVCMOS1.py, format/FormatSMVRigakuEiger.py, format/FormatSMVRigakuPilatus.py, format/FormatTIFFBruker.py, format/FormatTIFFRayonix.py, format/image.py, imageset.py, model/__init__.py, newsfragments/212.misc
This is to reflect changes added in a series of commits merged in pull cctbx/cctbx_project#516. When the cctbx repository next becomes stable, this will break the dxtbx tests that relied tests with no stderr output, because a warning is printed.
This pull request will fix those tests once those commits are used for testing.
=> Update boost.python → boost_adaptbx.boost.python

format/FormatCBFMini.py, format/FormatHDF5Sacla.py, format/FormatHDF5SaclaMPCCD.py, format/FormatHDF5SaclaRayonix.py, format/nexus.py, model/spectrum.h, newsfragments/209.misc, tests/format/test_FormatHDF5SaclaMPCCD.py, tests/model/test_spectrum.py
=> Use factor_ev_angstrom from cctbx

imageset.py, newsfragments/214.bugfix, tests/test_imageset.py
=> Fix for loading imageset with '%' char in filepath

newsfragments/234.feature, sequence_filenames.py, tests/test_sequence_filenames.py
Necessary for proper importing of dumped 0mq packets
=> Pick up template for imageNNNNN e.g. what we use for 0mq dump

format/FormatXTCJungfrau.py, newsfragments/246.feature
Prolly doesn't need a review.  I'll merge after the tests pass and I add a news fragment.
=> Jungfrau XTC: read distance from XTC

.azure-pipelines/ci-conda-env.txt, newsfragments/257.misc
Friend of https://github.com/dials/dials/pull/1495
=> Use h5py >= 3.1

__init__.py, libtbx_refresh.py, newsfragments/281.removal
in preparation to move to 'main'.
Closes #281
=> Deliberately break the 'master' branch

format/FormatNexusEigerDLS16MI03.py, newsfragments/348.bugfix, tests/format/test_FormatNexusEigerDLS16MI03.py
Time-limited masking from 2021_04_22 till 2021_05_03 (inclusive).
=> Temporarily mask bad modules on DLS I03 Eiger

newsfragments/428.feature, src/dxtbx/format/FormatNXmx.py, src/dxtbx/nexus/nxmx.py, tests/nexus/conftest.py, tests/nexus/test_nxmx.py
Beamline I19 at Diamond Light Source now has four detectors, two of which produce NeXus data.  Support both of these NeXus data sources.
=> Support the I19 Tristan detector in FormatNXmx

src/dxtbx/boost_python/imageset_ext.cc, src/dxtbx/datablock.py, src/dxtbx/format/Format.py, src/dxtbx/format/FormatMultiImage.py, src/dxtbx/imageset.h, src/dxtbx/imageset.py, src/dxtbx/model/__init__.py, src/dxtbx/model/experiment.h, src/dxtbx/model/experiment_list.py, src/dxtbx/serialize/imageset.py, tests/model/test_experiment_list.py, tests/test_datablock.py, tests/test_imageset.py
Removed TOF/Rot ImageSequences. ImageSetData now has beams and sequence objects as python objects.
=> Simplified imagesets

newsfragments/481.bugfix, src/dxtbx/format/FormatNXmx.py
We don't have suitable test data for this yet.  :cry:
=> Add format class for I19-2 Eiger with DAC shadow

newsfragments/723.feature, src/dxtbx/format/FormatXTCRayonix.py
* defaults for detz_offset and cent_mm were calibrated using mfxl032222 (April 2024)
=> adds versatility to Rayonix XTC class

newsfragments/768.feature, src/dxtbx/model/experiment_list.py, tests/test_imageset.py
Give the user some hint as to the progress i.e. the computer is doing something when you import thousands of files.
Resolves dials/dials#2783
=> Add tqdm progress bar to dials.import

newsfragments/813.feature, newsfragments/818.bugfix, src/dxtbx/imageset.py
=> Revert "MemReader needs to know its format class to be used with FullCBFWriter"
