datablock.py, model/experiment_list.py, serialize/filename.py, serialize/imageset.py, tests/serialize/test_filename.py
`load_path` wasn't very descriptive; and implied that it was doing more work than just processing the pathname. `resolve_path` isn't perfect but is much better and doesn't suggest that it's doing any file reading.
In this patch I've kept `load_path` but it raises a DeprecationWarning when used; I don't know if this is treated as an external API so removing will break anything else? I'm happy to remove completely if nobody thinks this is the case....
=> Rename serialize.load_path to resolve_path

__init__.py
Temporary measure to apply the FPE flag inversion logic to dxtbx directly until a permanent resolution is found in https://github.com/cctbx/cctbx_project/pull/324
We have an increasing number of packages that depend on regular behaviour, and this is blocking us using eg. yaml downstream.
=> Invert FPE defaults for dxtbx

format/FormatMarIP.py
Similar to CBF format classes the header is identified using a binary
signature.
The original code required `header.find(signature)>0`, which excludes the case `header.startswith(signature)`. I assume this was by mistake - or at least that it does not matter, and changed it to `signature in header`.
Tagging @nksauter for review as original author.
=> Fix up MarIP detector format class

data/beamline_defs/__init__.py, format/FormatPYunspecified.py
This fixes `basestring` and `types.UnicodeType` usage.
There's only a couple of places in the code that use `basestring` explicitly.
- One of these doesn't need to
- One of these _does_ because it needs to identify str/unicode on 2 and str on 3
and one place that uses `UnicodeType`.
(Intention: Squash)
=> Python 3: basestring

format/Format.py
This pull request is based on the `libfuturize.fixes.fix_future_standard_library_urllib` fixer. In Python 3 `urllib2` is replaced by `urllib` and methods move around a bit. 
Tiny change, there is only one place where this is an issue.
=> Python 3: urllib

format/FormatPYunspecifiedStill.py
This pull request is based on the `libfuturize.fixes.fix_future_standard_library` fixer. This is the usual "`cpickle` becomes `pickle`" stuff, and this is just the futurize variant of the `six.moves` import.
Again, tiny change, there is only one place where this is an issue.
If you're wondering why there are two ways of achieving the same thing: The futurize constructs are made so that once the Python 3 move is complete one can just remove the two `from future import` / `install_aliases` lines from the top of every file and the result is pythonic Python 3 code. Whereas with `six` you may then have further rewriting to do before you can get rid of `six` and have clean Python 3 code.
=> Python 3: standard library

format/FormatMultiImage.py, imageset.py, model/experiment_list.py
This dramatically increases performance when deserialising experiment lists constructed as one-imageset-per-image, as they currently commonly appear to be[1] for still image sets. This reduces the load time to around ~5s for an example 11k image dataset. This is down from *too long to measure*, which is unsurprising given the "read every image for every image" loops it removes.
Some of the changes here aren't elegant solutions - there are some severe restrictions imposed by the data model and the cyclic nature of needing to resolve the format to construct an imageset in order to deserialize an imageset. These should be confronted, but at a later date.
I believe this overlaps with some of the 'Lazy' and 'load_models' solutions put in in the recent past:
- …
=> Faster deserialisation of still experiments via information reuse

example/to_xds.py, filecache.py, filecache_controller.py, format/Registry.py, model/__init__.py, model/beam.py, model/detector.py, model/detector_helpers.py, model/detector_helpers_types.py, model/goniometer.py, model/scan.py, model/scan_helpers.py, tests/model/test_detector2.py, tests/test_filecache.py
This pull request is based on the `libpasteurize.fixes.fix_newstyle` fixer.
Python 2 has two different class types, "old style" classes, which can be defined with
```python
class thing:
pass
```
and "new style" classes, introduced with Python 2.2 in 2001, can be defined with
```python
class thing(object):
pass
```
[The classes are subtly different](https://stackoverflow.com/questions/54867/what-is-the-difference-between-old-style-and-new-style-classes-in-python), for example `@property` decorators do not work properly on old style classes, and [with multiple inheritance the method resolution works differently](https://portingguide.readthedocs.io/en/latest/classes.html#method-resolution). This pull request first converts all remaining old style classes to new style classes - and then goes …
=> Python 3: libpasteurize.fixes.fix_newstyle

tests/test_regression_images.py
this tests iotbx functionality that is no longer used anywhere in dxtbx,
dials or xia2.
=> remove iotbx test from dxtbx

model/__init__.py, model/experiment_list.py
If anyone wants to take a look at this - I had a bit of a rampage through `ExperimentListDict`...
One of the victims was the pretend-class `ExperimentListDumper` which now is mostly gone and the remaining husk throws deprecation warnings.
This is by no means a finished product, but I hope a few steps in the right direction.
dxtbx and dials tests still pass, no dxtbx 3 regressions. There are flake8 warnings, but they are not new.
=> experimentlist refactoring

format/FormatHDF5EigerNearlyNexus.py, format/nexus.py
_If you remember nothing else, remember this:_
_**All strings in HDF5 hold encoded text.**_
_You can’t store arbitrary binary data in HDF5 strings. Not only will this break, it will break in odd, hard-to-discover ways that will leave you confused and cursing._
(http://docs.h5py.org/en/stable/strings.html#the-most-important-thing)
Basically change all string comparisons against `numpy.string_()`. (Alas we also have to tolerate NearlyNexus files, which contain `string` instead of `numpy.string_()`)
Not saying this is ideal. Or that everything works. In fact this does not make a single test pass, but it does make them fail in a different place.
No dials/dxtbx regressions.
=> fix python 3 bytes/strings issues in Nexus

format/FormatSMV.py, format/FormatSMVADSC.py, format/FormatSMVADSCSN445.py, format/FormatSMVADSCSN905.py, format/FormatSMVADSCSN915.py, format/FormatSMVADSCSN920.py, format/FormatSMVCMOS1.py, format/FormatSMVJHSim.py, format/FormatSMVNOIR.py, format/FormatSMVRigaku.py, format/FormatSMVRigakuSaturnNoTS.py, format/FormatSMVTimePix_SU.py
extract common get_raw_data spells into a common function
as part of this work I noticed that the following format classes are not covered by tests:
* FormatSMVADSCSN905
* FormatSMVADSCSN915
* FormatSMVADSCSN920
* FormatSMVCMOS1
* FormatSMVJHSim
* FormatSMVRigakuSaturnNoTS
* FormatSMVTimePix_SU_512x512
* FormatSMVTimePix_SU_516x516
=> Refactor SMV format classes

format/FormatXTCJungfrau.py
The subclass uses exactly the same constructor as the superclass, so
remove the constructor from the subclass.
As far as I can tell this code is not covered by tests, so might be useful to have a look before this goes into master.
=> XTCJungfrau: deduplicate code

format/FormatHDF5SaclaRayonix.py
During the recent round of beamtimes at SACLA, we identified that the fast axis convention for FormatHDF5SaclaRayonix is flipped (when compared with how the data is written out by the rayonix). This became obvious when looking at the kapton shadow along the beam from the source to sample direction (as can be seen in dials.image_viewer in the figure attached). The kapton 'line' should be tilted about the vertical axis by 10 degrees in the clockwise direction but is instead tilted in the anti-clockwise direction. This PR fixes it. The fast axis convention in this PR is also consistent with the FormatTIFFRayonix class when it is used on the raw image files. 
The second part of the changes relate to how the rayonix is configured. For our beamtimes, the rayonix was configured in 4x4 binning …
=> switch fast_axis to +x and configure rayonix based on binning size

format/nexus.py, newsfragments/75.bugfix
To fix https://github.com/cctbx/dxtbx/issues/74 - `NXgroup.visititems()`
does not follow soft links but probably it should, certainly this is a known
issue on the h5py lists. Added new implementation `local_visit` which behaves
as expected. Also found that `saturation_value` missing so worked around. Following up with SLS on that one.
=> New visitor implementation

.travis.yml, format/Format.py, format/FormatCBFFullPilatus.py, format/FormatCBFFullPilatusDLS300KSN104.py, format/FormatCBFFullPilatusDLS6MSN100.py, format/FormatCBFFullPilatusDLS6MSN126.py, format/FormatCBFMiniEiger.py, format/FormatCBFMiniEigerDLS16MSN160.py, format/FormatCBFMiniPilatus.py, format/FormatCBFMiniPilatusDLS12M.py, format/FormatCBFMiniPilatusDLS6MSN100.py, format/FormatHDF5SaclaMPCCD.py, format/FormatHDF5SaclaRayonix.py, format/FormatMultiImage.py, format/FormatNexusEigerDLS16M.py, format/FormatPYunspecified.py, format/FormatPYunspecifiedStill.py, model/experiment_list.py, newsfragments/70.feature, newsfragments/73.feature, tests/format/test_FormatHDF5SaclaMPCCD.py, tests/format/test_FormatPYunspecified.py
This pull requests resolves #70 (see also #65).
- Add an optional Format.get_static_mask() method to allow format classes to define a static mask to be used on all images.
- Add tests for static masks in FormatHDF5SaclaMPCCD and FormatPYunspecifiedStill.
- Remove superfluous Format.get_mask() functions - these are no longer called and the functionality they used to provide are provided elsewhere.
=> Format.get_mask() -> get_static_mask()

format/image.py, imageset.py, model/__init__.py
less `from x import *`
more `__all__=(...)`
=> Avoid * imports, explicitly declare exported symbols

SConscript, filecache.py, format/FormatCBFFull.py, format/boost_python/cbf_read_buffer.cpp, format/boost_python/cbf_read_buffer.h, format/boost_python/image_ext.cc, newsfragments/72.feature, tests/test_image_readers.py, tests/test_regression_images.py
Previously, miniCBF files could be read from a gzipped/bzipped file, but
fullcbf files could not, because they passed the filename through to
cbflib.
This patch writes some custom cbflib interaction code and uses an API
call that is unexposed via pycbf to pass through a data buffer when a
compressed file is detected. It also reintroduces a limited form of a
test to compress regression image data and verify reading.
Fixes #72.
=> Allow compressed FullCBF files to be read

imageset.h, newsfragments/90.misc
A small change to improve performance of get_corrected_data.
If not external gain map is set then the gain map is populated from the detector panel gain value. This is not very efficient, especially if the gain is 1.0 and the pedestal is 0.0.
This pull request implements a change to get_gain and get_pedestal which means that if the detector panel gain is 1.0 then an empty array is returned from get_gain and is pedestal is 0.0 an empty array is returned from get_pedestal. This results in a large improvement in performance during integration.
=> Improve performance of get_corrected_data

datablock.py, format/Format.py, newsfragments/89.bugfix, tests/test_datablock.py
Reduce the number of `open()` calls per file from 2 to 1 (10 to 1 for `.cbf.gz`) for `dials.import`.
Still 5 `stat()` calls per file.
Tests do not yet pass for this.
=> Reduce the number of file operations in dxtbx

format/nexus.py
Issue found testing data in prep for SwissFEL experiment.
Example dataset for the Jungfrau 16M detector is here:
https://zenodo.org/record/3352358#.XYJrbtNKj2I
local_visit was added in #75 to fix #74.  It's a replacement for h5py's visititems function, working around h5py/h5py#671.  The documentation for visititems says "Recursively visit all objects in this group and subgroups. You supply a callable...".  Note it doesn't say it visits itself (http://docs.h5py.org/en/stable/high/group.html).
So why wasn't this noticed before?  Because I think the only code that cares that self isn't visited is here:
https://github.com/cctbx/dxtbx/blob/master/format/nexus.py#L1200-L1202.
That's DetectorFactoryFromGroup, a function only used by multi-panel detectors that group modules into groups, which I …
=> local_visit should not check self

imageset.h
- Add an (internal) double-conversion function to `ImageSet` to avoid redundant conversions (this was being called twice by integrate).
- Even when there was no gain or pedestal to apply, the data was copied. This _does_ mean that the data from `get_corrected_data` is now the "original" image data and not a copy, which could _potentially_ cause problems if modified without copying, but this would require attempted access to the original without trying access something else.
=> Reduce unnecessary operations for dials.integrate

masking/goniometer_shadow_masking.h, model/boost_python/panel.cc, model/boost_python/parallax_correction.cc, model/parallax_correction.h, model/pixel_to_millimeter.h
Tidy up parallax correction API so that on both the Python and C++ side only functions named `parallax_correction` or `parallax_correction_inv` exist. These functions have overloaded definitions depending on whether panel data and precalculated `attenuation_length` exist.
=> Attenuation tidy

.pre-commit-config.yaml
Does what it says on the tin. Helps to maintain the sorted-imports state of the repo.
=> Add isort to pre-commit hooks

model/__init__.py, newsfragments/100.feature, tests/model/test_experiment_list.py
To try and make writing scripts more discoverable. As long as you know you want an ExperimentList, you should be work out how to load it.
Inline import used because at the moment there are recursive imports between ExperimentList injections and ExperimentListFactory.
=> Add ExperimentList.from_file

format/boost_python/image_ext.cc, format/boost_python/nexus_ext.cc, format/image.h, format/nexus.py, imageset.h, tests/test_image_readers.py
This allows reading NeXus data saved with double precision, such as either the JF16M corrected data or the JF16M gain map/pedestals.
Would appreciate a quick check from @graeme-winter ensuring this doesn't break DLS Eiger datasets.  Thanks :)
=> Add double version of dataset_as_flex_int

datablock.py, format/Registry.py, model/__init__.py, model/experiment_list.py, serialize/xds.py
These are all things that have been deprecated for a while now. I see no reason to keep them around for DIALS 2.1. Unless anyone objects I will merge this in a week or so.
* `out=` parameter removed for `xparm_xds()`
* `verbose=` parameter removed for classes
* `FormatChecker`
* `DataBlockTemplateImporter`
* `DataBlockFilenameImporter`
* `Beam.get_direction()` removed (#6, #68)
* `ExperimentListDumper` removed (#54)
* `Registry.lookup()` removed (#34)
* `Registry.Registry` removed (#34)
* Add formal deprecation warning for the
`as_str=` parameter in `XDS_INP()`
(cf. b2533d5a4afa5479daab99595c92620e92713023)
=> Remove deprecated classes/functions/parameters

run_tests.py
following dials/dials#890 we should also disable the ability to run tests via `libtbx.run_tests_parallel module=dxtbx`.
Reasons:
1. libtbx testing is entirely superseded by pytest.
2. test results are misclassified. libtbx testing only crudely recognizes skipped tests, and does not tell this information to the user. It indicates `OK` instead. Some passing tests that are perfectly fine are shown as `WARNING`. Expected failures are also shown as `OK`/`WARNING`.
3. optional tests depending on the `--regression` flag are not run, results are again shown as `OK`
4. none of the relevant explanatory text for test skipping or failure makes it into the output.
5. libtbx testing does not show any warnings/deprecationwarnings
6. none of the above is obvious to anyone running libtbx tests and people …
=> Disable libtbx testing for dxtbx

format/Format.py, format/FormatMultiImage.py, format/FormatXTC.py, newsfragments/124.misc
We currently use a global shared variable, which is not a good idea for many reasons.
Move it to the constructor instead.
=> Remove global shared state in Reader classes

imageset.py, model/experiment_list.py, model/scan.h, model/scan.py, newsfragments/118.feature, tests/model/test_experiment_list.py
Having looked at the loading of "proper" still image sets I found where the time was going. 
Even if we have one image set in the experiment list, the set was duplicated NN times because of the key on (imagset, scan) in the cache code. Working around this in the kinda-sorta stupid way which is in this branch makes things load in finite time. 
N.B. this still works against imageset-experiment-iterator branch in dials, though this is not strictly necessary. 
I do not think this code is worthy of merging, but it encodes some information - a map of the onion mines, if you like. 
#info @rjgildea @ndevenish @dagewa
=> Load before heat death

SConscript
This adds the Python version number, if necessary, to the Boost.Python library. This enables the linking of Boost libraries from conda packages. However, linking only works with compilers that are ABI compatible with the ones used to build the conda packages.
=> conda: get Boost library with Python version

imageset.py, newsfragments/133.bugfix
If we are grabbing a single image respect the offset (i.e. don't just use len(items) - fixes counting from 0 errors
Though we may not be fully out of the woods:
```
Extracted 538 spots
Removed 83 spots with size < 3 pixels
Removed 0 spots with size > 1000 pixels
Calculated 455 spot centroids
Calculated 455 spot intensities
Filtered 0 of 455 spots by peak-centroid distance
Histogram of per-image spot count for imageset 0:
```
Artefact? 🤔
=> Don't crash when finding spots in files with index 0

datablock.py, format/FormatBrukerPhotonII.py, model/detector.py, model/scan_helpers.py
For dxtbx to be general for Python (not just cctbx) people use proper Python built-in exceptions e.g. IndexError, ValueError. 
With this branch leaves Sorry in one area of code I have no business in and `command_line` which is fine. 
```
Grey-Area dxtbx :( [not-sorry] $ find . -name '*py' | xargs grep Sorry 
./format/FormatCBFMultiTileHierarchy.py:from libtbx.utils import Sorry
./format/FormatCBFMultiTileHierarchy.py:            raise Sorry("Unrecognized vector type: %s" % axis_type)
./command_line/radial_average.py:from libtbx.utils import Sorry, Usage
./command_line/radial_average.py:                    raise Sorry(
./command_line/radial_average.py:                    raise Sorry("Unrecognized argument '%s'" % arg)
./command_line/plot_detector_models.py:from libtbx.utils import Sorry …
```
=> Do not use Sorry in a library environment

imageset.py, newsfragments/141.bugfix
Because of the unique way we handle numbers (i.e. mishandle in most obfuscated way possible) images numbered 0 have index -1 which in turn makes for a lot of fun indexing `imageset[j:j+1]` since `imageset[-1:0]` _means_ something in Python; yay. Work around by grabbing the constructor arguments which were provided as input and correcting these; needs very substantial testing to ensure slicing to end of array or similar still works...
=> Handle slicing when images start from 0

model/goniometer.py, tests/test_goniometer.py
Previously overriding single-axis goniometer orientation in
dials.import only be done by using the geometry.goniometer.axes
parameter, but providing a single 3D axis. This commit adds an
'axis' parameter to give a more natural interface in that case.
=> Add goniometer.axis parameter.

command_line/image_average.py, format/FormatCBFMultiTile.py, format/FormatCBFMultiTileHierarchy.py, format/cbf_writer.py, model/detector.py, model/detector_helpers.py, tests/command_line/test_average.py
- Add a test for dxtbx.image_average that includes testing gain
- Modify full cbf format readers to read the gain
- Modify cbf_writer to use the gain
This does affect any processing that uses cbfs with a gain !=1.  See for example dials_regression/image_examples/SPring8_ADSC_SN916/Xtal17-2phi_3_015.cbf.  On master, dxtbx.print_header will report gain=1.  With this change, gain will be 1.84.
=> Use the gain for full cbf files 

format/nexus.py
We are writing NeXus master files for the SwissFEL JF16M detector using
https://github.com/cctbx/cctbx_project/blob/master/xfel/swissfel/jf16m_cxigeom2nexus.py
which is the same script used to make
https://zenodo.org/record/3352358#.Xmp9gRdKhpk
Works great in py2.  Files written in py2 also can be read in py3.  However, files written in py3 cannot be read in py3 without these changes.
From what I can tell, h5py is writing utf8 encoded strings in py3 to hdf5.  We are using numpy.string_ to test these strings in nexus,py, as recommended by the hdf5 documentation (http://docs.h5py.org/en/stable/strings.html).  In py3 this always returns bytestrings, but these new hdf5 files have attributes encoded as utf8.  Using more calls to numpy.string_ in nexus.py seems to resolve problems comparing …
=> Minimal fixes needed to get HDF5 files written in py3 to be read

model/experiment_list.py, tests/model/test_experiment_list.py
Otherwise this confusingly leads to an error under from_pickle_file.
Fixes #154
=> Don't swallow FileNotFoundError in ExperimentList.from_file

model/__init__.py, model/boost_python/crystal.cc, model/crystal.h, newsfragments/142.feature, tests/model/test_crystal_model.py, tests/serialize/test_crystal_model_serialize.py
Following discussion in #150, here is an alternative fix for #142.
The `Crystal` model is furnished with a new "recalculated cell" data member and associated errors. This is entirely independent of the existing static cell. The intention is to set this after some form of postrefinement. We don't want to wipe out the original static cell for this, because that cell was used for prediction, whereas this may not. The `recalc` cell plays a part in the `is_similar_to` iff both crystals have this cell set.
=> Recalculated cell

model/__init__.py, newsfragments/165.bugfix, tests/test_util.py, util/__init__.py
If standard_uncertainty < minimum then return value rounded to - log10(minimum) dp
Contributes fixes for some issues highlighted in https://github.com/xia2/xia2/issues/442
=> Make cell formatting sensible

format/FormatHDF5EigerNearlyNexus.py, format/FormatNexus.py, format/FormatNexusJungfrauHack.py, format/nexus.py
As of nexusformat/definitions#717, NeXus can support multiple wavelength files.  This pull request does two steps of refactoring:
1. Implement get_beam in FormatNexus and derived classes such that it takes an index.
2. Refactor the nexus.py BeamFactory to add a get_model method which takes an index. That way the beam model can be loaded on request as opposed to only in `__init__`.
Documentation for NXBeam as part of NXmx: https://manual.nexusformat.org/classes/applications/NXmx.html. Note the several available use cases, including a per-shot spectrum. These use cases are stubbed out in this pull request, and will be implemented at a later date.
This is a draft pull request because it requires #147.  After that is merged, I'll make this ready, but this request can be reviewed now.
=> Multi-wavelength NeXus

format/nexus.py, newsfragments/168.bugfix
Include head in dependency tree - fixes #168
Previously we were skipping the first thing that the sample depends on for FormatNeXus - not a problem before because sample depended on sample_x etc.
=> Fix sls eiger 168

datablock.py, format/Format.py, format/Registry.py, newsfragments/173.feature, tests/format/test_uri.py
This patch adds the ability to build `Format` classes such that `dxtbx.load("scheme://something")` will work - e.g. create a format class from a URL instead of a filename. This also works when passing things in through dials, e.g. `dials.import`. This works via checking for a scheme extracted via [urlparse](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse) - if a scheme is present then various file-based handling (open-read cache, absolute expansion) is bypassed.
A `Format` class must have the schemes it supports explicitly defined via the `schemes` attribute:
```python
def FormatScheme(Format):
schemes = ["scheme"]
```
where the default value for `schemes` is empty (`""`). If the format class does not declare support for a scheme, then it will not be called to …
=> Support Formats from "scheme://" URL identifiers

format/FormatHDF5EigerNearlyNexus.py, format/FormatNexus.py, format/FormatNexusJungfrauHack.py, format/nexus.py
While NXmx (currently) specifies NXbeam is required on the NXsample group, the NeXus base class NXinstrument also allows NXbeam.  A PR to modifiy NXmx to note beam can be on instrument instead is under preparation.
With this change the revised NeXus master file in https://zenodo.org/record/3526738#.XrNAABNKipr works.
=> Update nexus readers to find beam in both sample and instrument groups

format/nexus.py
Account for #169, where the first element of the depends on chain is now the input element. Fine for gonio/scan but doesn't work for multipanel detectors.
@graeme-winter could you run dials.import on your sls eiger file with and without this change and let me know if there is a difference?
This change is critical for the JF16M so let me know.  I'd like this merged ASAP if it doesn't affect things on your end.  THANKS.
=> Bugfix for hierarchical detectors in NeXus

datablock.py, format/Format.py, model/experiment_list.py, newsfragments/176.bugfix, tests/format/test_uri.py, tests/test_regression_images.py
Schema format support went in in e8282159908f0fa5254f204e75ed829a8ba86ac2.
There are a couple of issues with `datablock.json`, `Format.py` and `experiment_list.py` that got missed from that commit, that cause issues with reloading schema data from file e.g. several places that when loading, assume filenames and call `abspath`.
This adds tests and fixes those.
In addition, a problem where the duplicate-format test was not scheme-aware is fixed.
=> Fix issues reloading data with scheme:// format data sources

format/FormatSMVADSCSN442.py, newsfragments/171.bugfix
So check the datestamp - for #170 - if the date is after May 14th, 2007 then
read the BEAM_CENTER records not DENZO_ records
=> ADSC 442 moved to 5.0.1 in May, '07

format/FormatHDF5EigerNearlyNexus.py, format/FormatNexus.py, format/nexus.py, newsfragments/189.bugfix
For single-panel NeXus files anyway, read the actual array dimensions in
the data rather than the asserted image_size data set (which has historically
been _sometimes_ back-to-front so needs reversing sometimes) - removes the
known backwards as every case where that was relevent is now handled by
actually reading the proper array dimensions.
Fixes #184
=> Trust data dimensions not image_size

datablock.py
If image_range is set, then this is used as the expected first and last images, rather than by what matching files happen to be present on disk.
=> Support image_range in DataBlockTemplateImporter

boost_python/imageset_ext.cc
Following from warning from clang:
```
/Users/graeme/svn/cctbx/modules/dxtbx/boost_python/imageset_ext.cc:378:12: warning:
local variable 'result' will be copied despite being returned by name
[-Wreturn-std-move]
return result;
^~~~~~
/Users/graeme/svn/cctbx/modules/dxtbx/boost_python/imageset_ext.cc:378:12: note:
call 'std::move' explicitly to avoid copying
return result;
^~~~~~
std::move(result)
```
This seems to work in my hands
=> Move not copy data from imageset_ext

.pre-commit-config.yaml, command_line/detector_superpose.py, command_line/display_parallax_correction.py, format/FormatCBFCspad.py, format/FormatCBFFull.py, format/FormatCBFMini.py, format/FormatCBFMultiTile.py, format/FormatCBFMultiTileHierarchy.py, format/FormatNexus.py, format/FormatXTCCspad.py, format/FormatXTCJungfrau.py, format/FormatXTCRayonix.py, format/cbf_writer.py, format/nexus.py, model/beam.py, model/detector.py, model/goniometer.py, model/scan.py, newsfragments/211.misc, pyproject.toml, tests/test_image_readers.py, tests/test_split_singleimage_datablock.py
Isort had a big release (or set of releases), which makes it's classification of dependencies a lot more deterministic and reliable in the face of changing environments (https://github.com/timothycrosley/isort/issues/1147), as well as adding adds a load of controls for when it works.
This updates it, the main side-effect of is that `psana` and `pycbf` are now treated as third-party; this probably makes sense as a classification for import sorting. It also separates dials, which I've added in as an extra, manual section - it makes sense to keep this close to dxtbx where used, although we should probably try to remove these few recursive dependencies where they aren't protected.
=> Update isort to 5.4.2

command_line/print_header.py, format/FormatPY.py, format/FormatPYmultitile.py, format/FormatPYunspecified.py, format/FormatPYunspecifiedStill.py, newsfragments/205.bugfix
Current dxtbx testing for FormatPY uses pickles that were created using py2.  While reprocessing old LCLS data I regenerated some image pickles on a py3 build and found I couldn't read them because of encoding problems.  This PR fixes that problem using a new function in iotbx/npy.py, image_dict_to_unicode.
Additionally, this makes the understand method of FormatPY more robust.  Adds pickle protocol 4 magic bytes check but also tries to de-pickle the file, as the pickle magic bytes aren't guaranteed to fully specify whether a file is a pickle.
Note, the only place image pickles are generated in xfel land is averaging XTC streams with Rayonix data.  Everyting else, including xtc_process using Rayonix data, uses cbfs.
=> More PY3 support for FormatPY, the xfel legacy image pickle format

format/FormatSMVADSC.py, format/FormatSMVRigakuSaturnNoTS.py, newsfragments/216.bugfix, tests/format/test_FormatSMVADSC.py
Thanks to Christina Zimanyi on dials-support for the bug report:
```
File "/Applications/ccp4-7.1/lib/py2/site-packages/dxtbx/format/FormatSMVADSC.py", line 79, in _adsc_trusted_range
pedestal = int(self._header_dictionary.get("IMAGE_PEDESTAL", 0))
ValueError: Please report this error to dials-support@lists.sourceforge.net: invalid literal for int() with base 10: '93.0'
```
This appears to be triggered by an image file with a noninteger entry for `IMAGE_PEDESTAL`, whereas the code assumes that the header is always an integer - which has apparently held until now.
This fix just changes this to a float - it looks like it's always eventually passed into `DetectorFactory.make_detector`, which defaults and sets as floats anyway, so this shouldn't break anything.
I've added a test that rewrites …
=> Fix FormatSMVADSC breaking with non-integer pedestal

command_line/image_average.py, newsfragments/208.misc, tests/command_line/test_average.py
Fixes #207
Includes test for mpi (if available).
=> Use MPI reduce during image averaging

boost_python/imageset_ext.cc, imageset.h, newsfragments/218.bugfix, newsfragments/218.feature
Fixes memory leak in dials/dials@87929e297d81a20eec933ea6b6b006db5a75972c
In MPI mode, transmitting only the index into the experiment list is much faster than transmitting a sliced experiment list.  However, the slices now stay in memory instead of going through MPI pickling and thus falling out of scope. This causes a leak because of the caching in imageset.  Adding the ability to clear the cache means the memory can be freed, and later, the imageset can be serialized (especially relevant for composite mode).
Corresponding PR to dials.stills_process will be issued when this is approved.
=> Clear cache

SConscript
This is for building `dxtbx` with dependencies located in a general `$PREFIX` directory (e.g. a `conda` environment).
By overwriting `LIBPATH` in the SCons environment, any additional paths that are added outside of this `SConscript` are lost. This pull request changes the replacement with appending the paths in the current environment.
=> scons: prevent LIBPATH from being overwritten

format/FormatCBFMiniPilatusDLS12M.py, newsfragments/220.bugfix, tests/format/test_FormatCBFMiniPilatusDLS12M.py
The detector was serviced/cleaned during shutdown 3 and therefore no longer has any bad modules.
=> Update i23 bad pixel mask

newsfragments/225.misc, tests/format/test_FormatHDF5EigerNearlyNexus.py
Add a simple check that the image data can be read, which is where CCP4 builds of DIALS have failed in the past.
=> Exercise getting image data out of the NearlyNexus format

command_line/debug_memory.py, command_line/depends_on.py, command_line/detector_superpose.py, command_line/display_parallax_correction.py, command_line/dlsnxs2cbf.py, command_line/image2pickle.py, command_line/install_format.py, command_line/overload.py, command_line/plot_detector_models.py, command_line/print_header.py, command_line/print_matching_images.py, command_line/radial_average.py, command_line/read_sequence.py, command_line/saturation.py, command_line/show_mask_info.py, command_line/show_matching_formats.py, command_line/show_registry.py
Similar to dials/dials#1435, this makes the command_line/ scripts all runnable the same way:
- Every script has a run(args=None) method
- Cleaned up show_registry a bit as handling args or None was messy
- Removed Script pattern in detector_superpose
- Added simple `ArgumentParser` handling to many of the scripts that opaquely selected or sliced sys.argv
=> Unify script handling in command_line/

command_line/pytest_launcher.py
effectively moving it downstream from libtbx (cctbx/cctbx_project#540) until we can fix the underlying issue.
This needs to be merged at roughly the same time. Developers may encounter an error such as
```
RuntimeError: Multiple sources for dispatcher:
target file:
"build/bin/pytest"
source files:
"modules/cctbx_project/libtbx/command_line/pytest_launcher.py"
=relocatable_path(anchor="build", relocatable="../modules/cctbx_project/libtbx/command_line/pytest_launcher.py")
"/scratch/wra62962/files/dials/modules/dxtbx/command_line/pytest_launcher.py"
=relocatable_path(anchor="build", relocatable="../modules/dxtbx/command_line/pytest_launcher.py")
```
on reconfiguring. This means that the `cctbx_project` repository is out of date and needs updating.
=> Add a pytest launcher to dxtbx

newsfragments/235.bugfix, util/dlsnxs2cbf.py
So just take 1st 19 characters of timestamp; good for another 7980 years or so.
=> Strip timezone

format/FormatSMVADSC.py, newsfragments/242.bugfix
This is based on  pragmatic acceptance that FormatSMVADSC will recognise
more than just ADSC CCD detector images (see #161). Images where GAIN
is set in the header should use this value rather than do the ADSC
module GAIN guesswork.
=> Allow gain set in the SMV header to override guesswork

format/nexus.py, newsfragments/240.bugfix
Using dataset.name doesn't work here if using hardlinks, as dataset.name will be the name of the field in the linked to file, instead of the name of the field in the master file.
=> Hardlink fix for NeXus files

model/beam.py, newsfragments/243.feature
For wavelengths shorter than 0.05 Å, set an unpolarised beam model as we assume electron diffraction. Fixes #241.
=> Set unpolarised beam for very short wavelength

.azure-pipelines.yml, .azure-pipelines/unix-build.yml, conftest.py, datablock.py, format/Format.py
This runs the Azure tests in [Python Development Mode](https://docs.python.org/3/library/devmode.html).
Right now a few tests are still failing as they depend on 
being merged,
=> Run Azure tests in Python development mode

datablock.py, newsfragments/247.removal, serialize/dump.py, tests/test_split_singleimage_datablock.py
As far as I can tell we don't dump datablocks anywhere any more (apart from the one test touched by this commit)
So I think we might be able to remove this?
Suggest adding deprecation notices for now, see how it goes, backport to 3.2.1, and then remove in time for 3.3
=> Deprecate DataBlock Dumping

newsfragments/248.removal, serialize/dump.py, serialize/filename.py, serialize/xds.py, tests/serialize/test_filename.py
* remove `dxtbx.serialize.dump.experiment_list` (deprecated 07/2019)
* remove `dxtbx.serialize.filename.load_path` (deprecated 05/2019)
* remove the `as_str` argument of `dxtbx.serialize.xds.to_xds().XDS_INP()` (deprecated 11/2019)
* left one flake8 warning (unused `import warnings`) to avoid a conflict with #247
=> Remove historic deprecations

format/FormatXTCEpix.py, format/FormatXTCJungfrau.py, newsfragments/250.feature
The pixel values reported by the Jungfrau and ePix detectors are in units of keV.  Because of this, we have been using two settings in dials.stills_process to handle the data:
spotfinding.threshold.gain=9.8
integration.summation.detector_gain=9.8
Here, 9.8 is a surrogate for the average beam energy in keV over the whole run.  The first parameter sets the gain for spotfinding to work and the second parameter is used as a scalar during integration, applied to the intensity variance (see Eq 11 of Leslie 1999).  In Brewster 2019 we showed this made a big difference for handling errors.
Fine and good.  We processed most of the data from the Sept-Oct 2020 LCLS experiments this way.  But doing it this way ignores the shot-to-shot variation in energy. This PR changes FormatXTCJungfrau and …
=> Use energy in keV for the gain for the ePix and JungFrau detectors at LCLS

.azure-pipelines/ci-conda-env.txt, libtbx_config, newsfragments/260.misc, tests/test_datablock.py, tests/test_filecache_controller.py
and use the standard library implementation (`unittest.mock`) instead of the `mock` package.
This is independent of the `pytest-mock` PRs going around in parallel
=> drop dxtbx mock dependency

.azure-pipelines/ci-conda-env.txt, __init__.py, newsfragments/258.removal
Pick up the plugins from their correct location.
Don't override the HDF5 plugin path if one is given in the environment.
Existing installations should update their hdf5-external-filter-plugins package.
Resolves #256
=> Fix HDF5 plugin handling

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/unix-build-v2.yml
This adds an Azure Linux Python 3.6 build using the conda-forge cctbx package rather than building cctbx from scratch.
Background: https://dials.github.io/kb/core/20201015#cctbx-conda-forge-package
=> Add an Azure build based on the cctbx release

format/FormatMultiImage.py, newsfragments/227.bugfix
Separating bugfix from #227 by @dwpaley
> Bugfix in FormatMultiImage: If we're creating an ImageSetLazy, we still need to get the static mask from the format class and add it to the imageset.
>
> Co-authored-by: Aaron Brewster <asbrewster@lbl.gov>
=> Apply static format masks to Lazy ImageSets

model/scan.h, newsfragments/271.feature
I've often wanted to quickly get the number of images from `dials.show` output, but sometimes this involves mental arithmetic and is not particularly `grep` friendly.
```
Scan:
image range:   {74,660}
oscillation:   {0,0.0344}
exposure time: 0.1
```
It seems to me it would be useful to also have a `number of images` field. This PR adds that:
```
Scan:
number of images:   587
image range:   {74,660}
oscillation:   {0,0.0344}
exposure time: 0.1
```
=> Add number of images to Scan ostream.

format/nexus.py
From limited testing, there doesn't appear to be any performance difference between default and `swmr=True`.
Using master (on a machine with 4 cores):
```
$ time dials.find_spots /dls/i04/data/2020/cm26459-3/xraycentring/manual/xrc_43_master.h5
real	0m36.562s
user	1m24.326s
sys	0m25.553s
```
Using this branch:
```
$ time dials.find_spots /dls/i04/data/2020/cm26459-3/xraycentring/manual/xrc_43_master.h5
real	0m36.870s
user	1m25.365s
sys	0m25.619s
```
=> Enable SWMR-mode reading NeXus files

format/FormatHDF5EigerNearlyNexus.py, format/nexus.py, newsfragments/285.bugfix, tests/format/test_nexus.py
Fix bug in `nexus.DataFactory` that allowed access to twice as many images as available on disk for VDS nexus files.
If the node contains a VDS, then only use this dataset.
Fixes #285
=> DataFactory: if VDS don't also include individual external datasets

command_line/debug_memory.py, command_line/depends_on.py, command_line/detector_superpose.py, command_line/display_parallax_correction.py, command_line/dlsnxs2cbf.py, command_line/image2pickle.py, command_line/image_average.py, command_line/install_format.py, command_line/overload.py, command_line/plot_detector_models.py, command_line/print_header.py, command_line/print_matching_images.py, command_line/radial_average.py, command_line/read_sequence.py, command_line/saturation.py, command_line/show_mask_info.py, command_line/show_matching_formats.py, command_line/show_registry.py, newsfragments/306.bugfix, util/__init__.py
where the output is redirected away from the console into a pipe or file. For this we need to ensure that stdout/stderr are UTF-8 encoded.
Closes DiamondLightSource/python-procrunner#88
=> Avoid crashes on Windows when printing unicode

datablock.py, format/test_cbf_mini_as_file.py, model/compare.py, model/experiment_list.py, newsfragments/302.misc
`BeamDiff`, `ScanDiff`, `GoniometerDiff`, `DetectorDiff`, `SequenceDiff` in `dxtbx.datablock` are replaced by functions in `dxtbx.model.compare` (`beam_diff`, etc.)
They don't really have anything to do with datablocks or experiment lists.
=> Deprecate datablock.*Diff pseudoclasses

command_line/dlsnxs2cbf.py, newsfragments/309.bugfix, newsfragments/309.doc, tests/command_line/test_dlsnxs2cbf.py
It seems you should be able to get a help message by calling `dxtbx.dlsnxs2cbf -h`:
```
$ dxtbx.dlsnxs2cbf
usage: dlsnxs2cbf.py [-h] nexus_file template
dlsnxs2cbf.py: error: the following arguments are required: nexus_file, template
```
but instead I get a traceback:
```
$ dxtbx.dlsnxs2cbf -h
Traceback (most recent call last):
File "/dls_sw/apps/dials/dials-v3-3-3/build/../modules/dxtbx/command_line/dlsnxs2cbf.py", line 17, in <module>
run()
File "/dls_sw/apps/dials/dials-v3-3-3/build/../modules/dxtbx/command_line/dlsnxs2cbf.py", line 12, in run
options = parser.parse_args(args)
File "/dls_sw/apps/dials/dials-v3-3-3/conda_base/lib/python3.8/argparse.py", line 1768, in parse_args
args, argv = self.parse_known_args(args, namespace)
File …
```
=> Fix dxtbx.dlsnxs2cbf help message

boost_python/compression.cc, newsfragments/352.bugfix
This fixes the assertion error raised in the azure build (See #351)
Presumably the comparison is made against a 32 bit signed int as the static value, and 0x80000000 is _not_ a valid signed 32 bit integer value
=> Remove useless assert

model/experiment_list.py, newsfragments/333.removal
previously deprecated in #333 (March 2021)
=> remove ExperimentListTemplateImporter

newsfragments/387.bugfix, tests/command_line/test_dlsnxs2cbf.py, util/dlsnxs2cbf.py
At present, `dlsnxs2cbf` expects the goniometer to have a φ and a χ axis.  Relax that assumption and only add φ and χ details to the CBF header if they are present in the NeXus file.
=> Accept a missing χ or φ axis in dlsnxs2cbf

.azure-pipelines/azure-pipelines.yml, .azure-pipelines/unix-build.yml, .azure-pipelines/windows-build.yml, newsfragments/396.misc
that runs up to the 'base' installation stage, at which point it is blocked by conda-forge/cctbx-base-feedstock#28.
First steps for #396
=> Add Windows build job to Azure CI

SConscript, newsfragments/392.bugfix, src/dxtbx/boost_python/flumpy.cc, tests/test_flumpy.py
Flex still doesn't bind `long long` on Windows, but does bind `int64_t` as a separate flex instance. This binds to it.
=> Fix 64-bit integer flumpy bindings on Windows

newsfragments/398.bugfix, src/dxtbx/boost_python/flumpy.cc
This prevents errors when trying to convert to flex arrays, when scitbx
hasn't been loaded yet.
Fixes #398.
=> Import flex when loading flumpy

newsfragments/411.bugfix, src/dxtbx/masking/goniometer_shadow_masking.h
Using an enum constant in a boolean context does not make sense in the
program and it generates a compiler warning in gcc.  This code change is
an educated guess as to the originally intended meaning.
=> Fix the 'int-in-bool-context' compiler warning.

libtbx_refresh.py, newsfragments/410.bugfix
Fixes #410.
`--no-build-isolation` bypasses the PEP-517/PEP-518 system where pip installs the build-time requirements in an isolated environment: see https://pip.pypa.io/en/latest/cli/pip/#pep-517-and-518-support. This was causing network access even with `--no-deps`. Combining `--no-build-isolation` and `--no-deps` appears to avoids triggering my outgoing firewall, and works when network is disconnected.
This appears to fail installation if not all the required base packages are present (e.g. `wheel`), because it cannot go fetch them. But since the `libtbx_refresh` stage will always be run in a managed environment, this restriction should be acceptable.
=> Allow offline configuration vis libtbx.refresh

newsfragments/405.bugfix, src/dxtbx/boost_python/flumpy.cc, tests/test_flumpy.py
As per https://github.com/cctbx/dxtbx/issues/405, passing non-contiguous arrays into flumpy comes up with an obscure and unhelpful exception:
```
>>> flumpy.from_numpy(np.zeros((256,256,256))[0:1,1:255,1:255])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'numpy.ndarray' object has no attribute 'obj'
```
Unfortunately, there seems to be no way to use the scitbx flex array bindings in a way that allows this conversion, so with this patch it is explicitly failed with a more helpful message:
```
>>> flumpy.from_numpy(np.zeros((256,256,256))[0:1,1:255,1:255])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: numpy array is non-contiguous - flex arrays must be contiguous
```
=> flumpy: Explicitly fail for non-contiguous numpy arrays

newsfragments/406.bugfix, src/dxtbx/boost_python/flumpy.cc, tests/test_flumpy.py
This could happen in cases where you are converting e.g. a contiguous slice of your original array - flumpy previously needlessly (and erroneously) assumed that if an array didn't own it's own data, that the array base came from flex.
Fixes #406
```
>>> data = numpy.zeros(100)
>>> flumpy.from_numpy(data[:])
<scitbx_array_family_flex_ext.double object at 0x7fe025c7abc0>
```
=> flumpy: Fix conversion of non-owning arrays

newsfragments/415.bugfix, src/dxtbx/boost_python/flumpy.cc
Previously, types were manually mapped between numpy [types](https://numpy.org/doc/stable/reference/arrays.scalars.html) and the types bound by flex. However, this caused several issues to do with cross-platform behaviour e.g. differences between when numpy gives you `q` and `l` types, and windows/linux differences in type sizing; see e.g. #415, #392.
This changes flumpy to map binded integer types directly (bool, int, long), and all other integer types are matched by signed/unsigned and integer width. This should eliminate this class of problems.
=> `flumpy`: More comprehensively handle type conversions

newsfragments/456.bugfix, src/dxtbx/format/FormatSMVJHSim.py
- default pedestal to 0 not 1
- trusted_range actually starts at the first untrusted value (#182)
With these changes, spots can be found on the attached zero noise image. Otherwise, the whole background is masked out and no spots are found.
[intimage_001.img.zip](https://github.com/dials/dxtbx/files/7661170/intimage_001.img.zip)
=> Fix problems with image pedestal in FormatSMVJHSim

.azure-pipelines/ci-conda-env.txt
The generation on Clang 14 appears to be incorrect for this combination of boost, python. In particular, in https://github.com/cctbx/dxtbx/blob/23f28fffb8f78321fa89e786b6c8e9aaefec4ea0/src/dxtbx/boost_python/ext.cpp#L196-L198, the generated assembly appears to early-call `_Py_Dealloc` near the top of the function without any kind of zero protections or checks:
```
0x101c03be8 <+40>:   lea    rbx, [rip + 0x7d78]       ; "file"
0x101c03bef <+47>:   mov    qword ptr [rbp - 0x88], rbx
0x101c03bf6 <+54>:   mov    qword ptr [rbp - 0x30], 0x0
0x101c03bfe <+62>:   lea    r12, [rip + 0x7d67]       ; "count"
0x101c03c05 <+69>:   mov    qword ptr [rbp - 0x38], r12
0x101c03c09 <+73>:   xorps  xmm0, xmm0
0x101c03c0c <+76>:   movups xmmword ptr [rbp - 0x60], xmm0
0x101c03c10 <+80>:   mov    qword ptr …
```
=> Restrict conda-forge compilers for CI jobs

.azure-pipelines/azure-pipelines.yml, .azure-pipelines/ci-conda-env.txt, .azure-pipelines/windows-build.yml, newsfragments/604.misc
(To merge after https://github.com/cctbx/dxtbx/pull/607)
This updates prebuilt cctbx, and adds Windows to the platforms run by the azure CI. This was previously impossible due to https://github.com/conda-forge/cctbx-base-feedstock/issues/28, and apparently still causing problems as of https://github.com/cctbx/dxtbx/issues/396. Using the CMake build for windows (as well as mac and linux, which already use it) neatly sidesteps the issue.
Windows being the only platform missing has occasionally caused issues through things breaking on the windows build. https://github.com/cctbx/dxtbx/commit/c2706ed02f54985e2fb82dbc0a2ce9024125a1a, https://github.com/cctbx/dxtbx/commit/ec97f03ee1adfcab0ddf4800df8a5004411aa815 and https://github.com/cctbx/dxtbx/pull/607 were explicitly identified as things …
=> Run CMake CI build/tests on Windows

.azure-pipelines/unix-build.yml, .azure-pipelines/windows-build.yml, newsfragments/614.misc, src/dxtbx/model/boost_python/beam.cc, src/dxtbx/model/boost_python/detector.cc, src/dxtbx/model/boost_python/goniometer.cc, src/dxtbx/model/boost_python/multi_axis_goniometer.cc, src/dxtbx/model/boost_python/panel.cc
Unity builds are when all the sources for a single output object are joined together into a single translation unit before linking. It is a technique that can reduce compile times by preventing re-parsing (at cost of increase memory usage during compile).
I've had to move some of the dxtbx.model declarations into sub-namespaces, because these modules somewhat relied on the ODR not applying to separate, static models.
=> Tidy model_ext namespacing and turn on Unity builds

newsfragments/299.bugfix, src/dxtbx/model/detector.py
This is intended to fix #299
Multiple PHIL scope extracts are merged by panel id before panels are constructed, ensuring all overrides for a single panel are contained in the same object.
=> Easier override of panel geometry

newsfragments/439.bugfix, src/dxtbx/boost_python/flumpy.cc, tests/test_flumpy.py
Previously, a size (3,) array would have erroneously converted to a 0x3 length vec3.
This is now explicitly forbidden; you must pass at least a (0, 3) multidimensional array.
Fixes #439.
=> Flumpy: Don't allow converting 1D vectors to vec2/3

newsfragments/709.feature, src/dxtbx/format/FormatXTC.py
I originally opened https://github.com/dials/dxtbx/pull/198 , but the base repository was wrong!
So, in summary, this PR is for reprocessing XTC streams when you know the hit indices ahead of time. It works as expected when the psana datasource only includes a single run, but when doing things in multi-run mode, e.g. `ds = psana.Datasource("exp=cxily7829:run=21-26:idx")`, the indexing of events seems to get distorted. There are no "exceptions / code failures" from what I've seen, its just that the retrieved hits no longer correspond to what they were in the single run case. I honestly suspect its an issue with PSANA API not behaving as intended, most likely the bit where we get the event from the index, but it would be nice to trouble shoot for more eyes.
Long term, this could be useful …
=> Hit indices

.github/workflows/build_test.yml, newsfragments/978.misc
This should help avoid double-running when pushing to a PR
=> Only run actions on pushes to main

.bumpversion.cfg, CHANGELOG.rst, newsfragments/808.bugfix, setup.py, src/dxtbx/command_line/install_format.py
Bugfixes
--------
- ``dxtbx.install_format``: Fix for modern setuptools versions which drop legacy ``setup.py`` features. (#808)
=> DIALS 3.24.1

newsfragments/misc.XXX, src/dxtbx/model/boost_python/detector.cc, src/dxtbx/model/detector.h
This adds overloads to `Detector.get_ray_intersection` so that you can use it with arrays of s1 vectors.
Usage:
`>>> r = reflection_table.from_msgpack_file("indexed.refl")`
Original behaviour:
```
>>> detector.get_ray_intersection(r["s1"][0])
(0, (41.538954962474804, 161.85078625725504))
```
Using an array of s1 vectors returns a Tuple as the c++ `Detector::coord_type` has no Python converter and this seemed more useful:
```
>>> panel, xy = detector.get_ray_intersection(r["s1"])
>>> panel[0]
0
>>> xy[0]
(41.538954962474804, 161.85078625725504)
```
If you know the panel you can pass this in to only get the xy:
```
>>> xy = detector.get_ray_intersection(r["s1"], r["panel"])
>>> xy[0]
(41.538954962474804, 161.85078625725504)
```
This can be used to construct a vec3 flex array quickly. E.g: …
=> Add overloads for Detector.get_ray_intersection 
